spring.application.name=springmvc
#hello.springmvc 패키지와 그 하위 로그 레벨 설정
#logging.level.hello.springmvc=trace
#logging.level.root=info
#로깅 기본값은 info이다
#logging.level.hello.springmvc=info
logging.level.hello.springmvc=debug
